name: Manual Deploy

run-name: "${{ inputs.environment }} Deployment by @${{ github.actor }} - ${{ inputs.commit }}"

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      commit:
        description: The commit you would like to deploy
        required: true
        type: string

      environment:
        description: The Environment to Deploy to
        required: true 
        type: string

jobs:
  manual-deploy:
    name: Deploy infra to ${{ inputs.environment }}
    runs-on: [self-hosted, auto]
    environment:
      name: ${{ inputs.environment }}
    container: 325943998015.dkr.ecr.us-east-1.amazonaws.com/olympus-infra:${{ inputs.commit }}

    steps: 
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Clone main repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit }}   

      - name: Clone submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OLYMPUS_INFRA_PAT }}
          submodules: recursive
          ref: master  

      - name: Perform create-change-set for services in staging us-east-1
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}   
          olympus-infra create-change-set --env ${{ inputs.environment }} --template-name services --region us-east-1 --tag BFLY-${{ inputs.commit }}-${{ steps.date.outputs.date }}  

      - name: Perform create-change-set for services-regional in staging ap-southeast-2
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          olympus-infra create-change-set --env ${{ inputs.environment }} --template-name services-regional --region ap-southeast-2 --tag BFLY-${{ inputs.commit }}-${{ steps.date.outputs.date }}
    
      - name: Perform create-change-set for services-regional in staging ca-central-1
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          olympus-infra create-change-set --env ${{ inputs.environment }} --template-name services-regional --region ca-central-1 --tag BFLY-${{ inputs.commit }}-${{ steps.date.outputs.date }}

      - name: Perform create-change-set for services-regional in staging eu-central-1
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          olympus-infra create-change-set --env ${{ inputs.environment }} --template-name services-regional --region eu-central-1 --tag BFLY-${{ inputs.commit }}-${{ steps.date.outputs.date }}

      - name: Perform create-change-set for lambdas in staging us-east-1 
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          olympus-infra create-change-set --env ${{ inputs.environment }} --template-name lambdas --region us-east-1 --tag BFLY-${{ inputs.commit }}-${{ steps.date.outputs.date }}            
