name: 'JIRA Integration Check'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          regex: '^.*\[[A-Z]+-[0-9]+\].*$'
